spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      minimumIdle: 4
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
      auto-commit: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: 'classpath:db/db.changelog-master.yaml'
springdoc:
  show-actuator: true