spring:
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    hikari:
      minimumIdle: 4
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 300000
      auto-commit: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: 'classpath:db/db.changelog-master.yaml'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/irede_realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
jwt:
  auth:
    converter:
      resource-id: "db_irede_client"
      principal-attribute: "principal_username"






springdoc:
  show-actuator: true

