spring:
  application:
    name: db_irede
    admin:
      enabled: true
  profiles:
    include: 'presentation, infra'
management:
  info:
    env:
      enabled: true
    java:
      enabled: true
    build:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*, openapi, swaggerui, info"
        exclude: "env,beans"
info:
  application:
    name: ${spring.application.name}
    version: ${project.version}
    spring-boot-version: '@project.parent.version@'
