databaseChangeLog:
  - changeSet:
      id: 1725401000021-1
      author: Manoel Neto
      objectQuotingStrategy: QUOTE_ONLY_RESERVED_WORDS
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: pk_categories
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: creation
                  type: DATETIME
              - column:
                  name: active
                  type: TINYINT(1)
              - column:
                  constraints:
                    nullable: false
                  name: name
                  type: VARCHAR(100)
            tableName: categories

